export const recurssionTree ={
    name:"john",
    age:90,
    children:[
        {
            name:"marry",
            age:60,
        },
        {
            name:"arthur",
            age:60,
            children:[  
                {
                    name:"lily",
                    age:65,
                    children:[
                        {
                            name:"Hank",
                            age:60,
                        }
                    ]
                }
            ]
        }
    ]
}